chore(deps): bump github.com/bytedance/sonic to 1.15.0 for Go 1.26 support (#6841)
* chore(deps): bump github.com/bytedance/sonic to 1.15.0 for Go 1.26 support

Update https://github.com/bytedance/sonic to https://github.com/bytedance/sonic/releases/tag/v1.15.0
For
* https://github.com/bytedance/sonic/pull/898

Found in
* https://github.com/Homebrew/homebrew-core/pull/258912

Upgraded by performing:

```
$ go1.26rc3 build -v ./...
github.com/bytedance/sonic/internal/rt
# github.com/bytedance/sonic/internal/rt
../../../go/pkg/mod/github.com/bytedance/sonic@v1.14.0/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../go/pkg/mod/github.com/bytedance/sonic@v1.14.0/internal/rt/stubs.go:36:54: undefined: GoMapIterator
$ go get github.com/bytedance/sonic@latest && go mod tidy
go: added github.com/bytedance/gopkg v0.1.3
go: upgraded github.com/bytedance/sonic v1.14.0 => v1.15.0
go: upgraded github.com/bytedance/sonic/loader v0.3.0 => v0.5.0
go: upgraded github.com/cloudwego/base64x v0.1.5 => v0.1.6
$ go1.26rc3 build -v ./...
$
```

* chore(utils): update version range for json

bytedance/sonic, to include 1.26

Signed-off-by: Dwi Siswanto <git@dw1.io>

---------

Signed-off-by: Dwi Siswanto <git@dw1.io>
Co-authored-by: Dwi Siswanto <git@dw1.io>